# Generated by Django 3.1.4 on 2021-01-03 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_auto_20210104_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
