# Generated by Django 3.1.4 on 2021-01-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0003_tugas_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='deadline',
            field=models.DateField(),
        ),
    ]
