# Generated by Django 3.1.4 on 2021-01-05 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0005_auto_20210105_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='jam',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
