# Generated by Django 3.1.4 on 2021-01-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0006_tugas_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='jam',
            field=models.CharField(max_length=10),
        ),
    ]
